# Auto-generated by check-for-update-on-gitlab.sh
# git-ref: HEAD
{
  srcinfo = {
    url = "gitlab:llvm/llvmslicer";
    rev = "979a9c88b69063412436503f5439b96e05f0509d";
    sha256 = "1460aps34vg3d8xnrb1xlyrm80pbzglzy5i0dw8jmsiw9xvm06fc";
  };
  version = "2016-09-25";
}
