# Auto-generated by check-for-update-on-gitlab.sh
# git-ref: HEAD
{
  srcinfo = {
    url = "gitlab:llvm/llstrata";
    rev = "9f91423ca02f87189a0c8dd69ee11fe5a5329182";
    sha256 = "0bnjfhkfiw0af6d5l471b0ydqran87mzymnj1s8lcvx8985i2v57";
  };
  version = "2017-08-15";
}
